[default]
solc_version = "0.8.19"

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", tag = "v4.9.2" }
forge-std = { git = "https://github.com/foundry-rs/forge-std.git", tag = "v1.0.0" }